### ISSUE TITLE
SyntaxError building the docs

### ISSUE THREAD

**Issue by moorepants** [executablebooks/thebe#336]
I'm getting this error building the current master tip:
```
moorepants@agni:docs(release-docs)$ make html
Running Sphinx v3.4.0
making output directory... done
/home/moorepants/src/thebe/docs/node_modules/mkdirp/lib/opts-arg.js:7
    opts = { mode: 0o777, fs, ...opts }
                              ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at Object.load (/home/moorepants/src/thebe/docs/node_modules/requizzle/lib/loader.js:105:18)
    at Requizzle.requizzle (/home/moorepants/src/thebe/docs/node_modules/requizzle/lib/requizzle.js:87:31)
    at infectProxy (/home/moorepants/src/thebe/docs/node_modules/requizzle/lib/loader.js:79:31)
    at Module.targetModule.require.filepath [as require] (/home/moorepants/src/thebe/docs/node_modules/requizzle/lib/loader.js:97:44)
    at require (internal/module.js:20:19)

Sphinx error:
jsdoc found no JS files in the directories ['/home/moorepants/src/thebe/src']. Make sure js_source_path is set correctly in conf.py. It is also possible (though unlikely) that jsdoc emitted invalid JSON.
make: *** [Makefile:37: html] Error 2
```

I'm not sure what the `node_modules` director is or why it is present (it isn't in the source tree).

**Comment by choldgraf** [comment]
I've run into NPM errors before where if there is a `node_modules` folder in the folder that I run Sphinx, it tries to *build* some of the files in that folder and errors...I wonder if that's what's going on?

**Comment by moorepants** [comment]
I deleted it and now I'm getting other npm errors. It also isn't clear to me why npm needs to be part of running sphinx.

**Comment by choldgraf** [comment]
perhaps we can add it to the "exclude_patterns" of Sphinx instead of deleting the folder?

**Comment by moorepants** [comment]
I'll debug a bit later. That's about all I can spend time on today. Thanks!

**Comment by moorepants** [comment]
No longer getting this error.
