### ISSUE TITLE
Error: Failed to construct 'Worker' -- when trying to use JupyterLite

### ISSUE THREAD

**Issue by sskagemo** [executablebooks/thebe#664]
### Describe the bug

(Sorry if this is already documented elsewhere, I've tried to look through and search in existing issues and documentation, but I have to admit that this is a bit beyond my field of competence ...)

**context**
When I try to set up my page at https://sskagemo.github.io/pythonevangelisten.no/blog/2023/07/test-av-thebe-for-interaktiv-kode-i-nettleseren/ (sorry for the Norwegian ...) similar to your demo of JuypyterLite, here https://executablebooks.github.io/thebe/lite.html 

**expectation**
I expected it to work in a similar way

**bug**
But instead the code-block does not change to interactive mode (I have configured the code-selector with ```"selector": "code"```)

I've looked into the Chrome developer tools, and in the console I see the following error:

```console
tslib.es6.js:72 Uncaught (in promise) Error: Failed to construct 'Worker': Script at 'https://unpkg.com/thebe-lite@latest/dist/lib/328.thebe-lite.min.js' cannot be accessed from origin 'https://sskagemo.github.io'.
    at F.initWorker (kernel.js:32:16)
    at new F (kernel.js:18:29)
    at create (index.js:56:24)
    at async w.startNew (kernels.js:116:15)
    at async P.startNew (sessions.js:94:15)
    at async index.js:347:19
    at async t.startSession (restapi.js:89:11)
    at async c.startNew (manager.js:135:15)
```

**problem**
This is a problem for people trying to do what is documented here https://mystmd.org/thebe/quickstart-lite (at least that was what I was trying to do :-))

### Reproduce the bug

Test the code on https://sskagemo.github.io/pythonevangelisten.no/blog/2023/07/test-av-thebe-for-interaktiv-kode-i-nettleseren/ 

### List your environment

Chrome Versjon 114.0.5735.199

**Comment by stevejpurves** [comment]
Hi @sskagemo! thanks for reporting this.

Looks like there's a CORS issue stopping the service worker -- that's unexpected but perhaps the unpkg.com route laid out in the docs is going to be problematic for github pages.

The best thing to do would be to deploy the `thebe-lite` assets with your build, if you look at the github pages deploy of the [thebe example site](https://github.com/executablebooks/thebe/tree/gh-pages) you'll see that we deploy the javascript rather than trying to pick it up from cdn.

There is a script available in packages/core/bin/copy-thebe-assets.cjs that can help with the copy step (also see this PR for running that with `npx`) I'll need to update the docs to reflect this way of doing things.

**Comment by sskagemo** [comment]
Thank you, I'll try that!

**Comment by stevejpurves** [comment]
@sskagemo I've been working on iproving this -- still some way to go but see this repo for an example deployment setup https://github.com/stevejpurves/lite-quickstart-example and updated docs https://mystmd.org/thebe/quickstart-lite
